spring.application.name=chat
server.port=8071

spring.datasource.url=jdbc:mysql://localhost:3306/chat_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true





jwt.secret=V4n9xQ2mL7pR5tY8kH3zN6cD1sW0fJ4uB9eT2gA7yU5iO3pL8rS6mX1qC4vN0kH7
jwt.expiration=86400000
jwt.cookieName=chat_token
jwt.cookieSecure=false
jwt.cookieSameSite=Lax
jwt.cookieMaxAge=86400